version: '3.7'
name: 'bitcoin-lightning'

services:
  bitcoind:
    image: lightninglabs/bitcoin-core
    restart: always
    volumes:
      - ./volumes/bitcoin:/home/bitcoin/.bitcoin
      - ./volumes/bitcoin/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - ./volumes/bitcoin/wallets:/home/bitcoin/.bitcoin/wallets
    ports:
      - '8332:8332'
    healthcheck:
      test: curl --fail http://localhost:8332/rest/chaininfo.json || exit 1
      start_period: 120s
      interval: 30s
      timeout: 60s
      retries: 10
    command: >
      bitcoind -conf=/home/bitcoin/.bitcoin/bitcoin.conf

  lnd:
    image: lightninglabs/lnd:v0.16.4-beta
    restart: always
    volumes:
      - ./volumes/lightning:/root/.lnd
      - ./volumes/lightning/lnd.conf:/root/.lnd/lnd.conf
    ports:
      - '8080:8080'
    healthcheck:
      test: 'curl --fail --insecure --header "Grpc-Metadata-macaroon: $MACAROON" https://localhost:8080/v1/getinfo || exit 1'
      start_period: 120s
      interval: 30s
      timeout: 60s
      retries: 10
    depends_on:
      bitcoind:
        condition: service_healthy
    command: >
      lnd --configfile=/root/.lnd/lnd.conf --bitcoin.mainnet

  lnbits:
    image: lnbitsdocker/lnbits-legend
    restart: always
    volumes:
      - ./volumes/lightning:/app/.lnd
      - ./volumes/lnbits/data:/app/data
      - ./volumes/lnbits/.env:/app/.env
    ports:
      - '5000:5000'
    healthcheck:
      test: curl --fail --insecure https://localhost:5000/api/v1/health || exit 1
      start_period: 60s
      interval: 60s
      timeout: 30s
      retries: 10
    depends_on:
      lnd:
        condition: service_healthy
    command: >
      poetry run lnbits --ssl-keyfile /app/.lnd/tls.key --ssl-certfile /app/.lnd/tls.cert

  thunderhub:
    image: apotdevin/thunderhub:v0.13.20
    restart: always
    volumes:
      - ./volumes/lightning:/app/.lnd
      - ./volumes/thunderhub/.env:/app/.env
      - ./volumes/thunderhub/accounts.yml:/app/accounts.yml
    ports:
      - '4000:4000'
    depends_on:
      lnd:
        condition: service_healthy

  nginx:
    image: nginx:1.25.1-perl
    restart: always
    volumes:
      - ./volumes/lightning:/app/.lnd
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '443:443'
    depends_on:
      - lnbits
      - thunderhub
